
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  # This is the gateway shared in knative service mesh.
  gateways:
    - knative-ingress-gateway.knative-serving.svc.cluster.local
  hosts:
    - api.{{ .Values.domain }}
  http:
    - match:
        - uri:
            prefix: '/{{ .Release.Name }}/'
        - uri:
            exact: '/{{ .Release.Name }}'
      rewrite:
        uri: '/'
        authority: {{ .Release.Name }}.{{ .Release.Namespace }}
      route:
        - destination:
            host: {{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: {{ .Values.httpPort }}

